### ISSUE TITLE
creation of Bulkaddresses and switching the language does not work

### ISSUE THREAD

**Issue by lottoicoind** [pointbiz/bitaddress.org#102]
Hey there,

i cloned the html file and changed everything needed for another altcoin. everything works fine except for two things: 
1. Switching language, it always stays at english
2. Generation of bulkaddresses. if i click on bulkaddresses on the orginal html, 3 addresses show up instant, in my clone happens nothing. even if i click on generate. i checked the code with winmerge against each other but i cant find any typos or something like that. any hints what part of the code i have to check? thank you

**Comment by pointbiz** [comment]
Issues with your fork should be submitted to your forked project.
