### ISSUE TITLE
Forget the Private Key of cold wallet

### ISSUE THREAD

**Issue by w7726c** [pointbiz/bitaddress.org#115]
I forget my private key for a cold wallet that create by bitaddress.Do we have any method to get back my bitcoin from the cold wallet? The cold wallet is "1CD9WH59K1rJBx1QM1XU3h7SuJqqugi4kD".I can't find any suppport in the page of bitaddress.

**Comment by danielsun174** [comment]
No you can not. Your "cold wallet" is actually your bitcoin-address key which is generated from the public key.
see [http://readwrite.com/2014/01/13/what-happens-to-lost-bitcoins/](http://readwrite.com/2014/01/13/what-happens-to-lost-bitcoins/)

**Comment by pointbiz** [comment]
You cannot recover the private key from the bitcoin address.
