### ISSUE TITLE
.html

### ISSUE THREAD

**Issue by TheButterZone** [pointbiz/bitaddress.org#121]
At the bottom... 
The "zip" hyperlink to https://github.com/pointbiz/bitaddress.org/archive/v3.2.0.zip is not found.
The "sig" hyperlink points to javascript:window.location=window.location.pathname+'.sig';

**Comment by pointbiz** [comment]
Thanks.
Fixed the zip. I published the release here.
The sig hyperlink is correct. It will download the .sig based on the file name of the current page.

**Comment by TheButterZone** [comment]
FF44.0.2 doesn't download anything based on that Javascript, it just opens a new tab with about:blank in it and nothing appears in the Downloads list.
