### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by ffxsam** [pointbiz/bitaddress.org#127]
Just a question for anyone who might want to contribute: it looks like the app's code (libraries aside) exists entirely in https://github.com/pointbiz/bitaddress.org/blob/master/bitaddress.org.html. Is this the case?

**Comment by pointbiz** [comment]
https://github.com/pointbiz/bitaddress.org/tree/master/src

**Comment by ffxsam** [comment]
Weird, how on earth did I miss that? Did it not exist back in May? Thanks!

**Comment by pointbiz** [comment]
Yes. You're welcome.
