### ISSUE TITLE
Wallet Details Hangs on Bad Private Key

### ISSUE THREAD

**Issue by avnr** [pointbiz/bitaddress.org#137]
When the private key that was entered is syntactically conforming but the checksum doesn't match, the code throws a checksum error exception but doesn't do anything with it. From the user's point of view the script just hangs. Should be some message such as the one generated for a misformed keys.

BTW, same misbehavior when the key is 0x0000000000000000000000000000000000000000000000000000000000000000

**Comment by pointbiz** [comment]
Related to this issue: https://github.com/pointbiz/bitaddress.org/issues/93

**Comment by pointbiz** [comment]
Closing this issue. Follow this issue for updates: https://github.com/pointbiz/bitaddress.org/issues/93
