### ISSUE TITLE
Wallet Details mislead the user to send BTC into black hold

### ISSUE THREAD

**Issue by bom64** [pointbiz/bitaddress.org#144]
Wallet Details tab mislead the user to send BTC to a BTC address without access to the corresponding Private Key (black hold) and the BTC is then lost. One of the two address have no relationship to the Private Key.

How to reproduce:

Navigate to https://www.bitaddress.org/bitaddress.org-v3.3.0-SHA256-dec17c07685e1870960903d8f58090475b25af946fe95a734f88408cef4aa194.html

Navigate to Wallet Details tab

Paste or key in any Private Key in any format (as far as I know) next to the label "Enter Private Key", eg
5JHo8mya6Qi62mwqD3u2rArC5gHMfbxvCW9TjmtgaSQfgdfwzhF

Click "View Details"
Two address is produced:
Bitcoin Address: 
18VxeqVC9C1oQEh164GQhLnWvLiLPuc4br

Bitcoin Address Compressed
1X1gJcn9Dbdy3ej2ZRuqbidU3de437pYM

Explore the two BTC address on any blockchain information services, eg  
blockchain.info
live.blockcypher.com/
btc.com

18VxeqVC9C1oQEh164GQhLnWvLiLPuc4br
have at press time 97 tx.
1X1gJcn9Dbdy3ej2ZRuqbidU3de437pYM
have at press time 0 tx. (But after my test the address have 1 tx)

I have for test reason send with low fee 12.34 bit or μBTC to 1X1gJcn9Dbdy3ej2ZRuqbidU3de437pYM, so now the address have 12.34 and 1 tx.

18VxeqVC9C1oQEh164GQhLnWvLiLPuc4br still have 97 tx.

For some Private Key it is "Bitcoin Address" that is correct, for other Private Key (I have one) the correct address is the Bitcoin Address Compressed. It mean that there are 50% risk for select the wrong address.

If the user calculate the bitcoin address for a Private Key for verification before send BTC to the address and believe that both address showed in the Wallet Details is connected to the Private Key show on the top and select the “wrong” address then the users BTC is lost if there is no way to calculate the Private Key to the "fake" address. 

I have not tested if the issue also is active if the user use a dice for creating a secure random address... 

Users that have downloaded v3.3.0 for offline use is in risk to lose BTC and need to be warned. 

https://bitcoinpaperwallet.com have same issue. 

It is a severe bug that spread insecurity to bitcoin and need to be fixed fast!

**Comment by patrikr** [comment]
Uh, the private key for 1X1gJcn9Dbdy3ej2ZRuqbidU3de437pYM is listed further down the page. (Starts with KyK8d...) Just import that key.

**Comment by bom64** [comment]
The issue don't mislead the user to send BTC into black hold. Compressed address and compressed keys is linked by design.
