### ISSUE TITLE
Bitaddress's stance on segwit2X

### ISSUE THREAD

**Issue by stale2000** [pointbiz/bitaddress.org#150]
Hello,

I am curious what bitaddress's stance is on segwit2X.  

Does bitaddress support segwit2X and will it be segwit2X ready by November?

Thank you!

**Comment by vv01f** [comment]
I cannot see where the question addresses the project. What part are you curious about?

* Bitaddress is a tool on addresses
* SegWit is about the transaction format
* the 2x part is about blocksize increase

Bitaddress does not create any transactions – the site brainwallet.org that did this is gone.

**Comment by jaonoctus** [comment]
+1

**Comment by farhan-shahid** [comment]
From what I understand bitaddress is just a Bitcoin address generator which has nothing to do with segwit2X. Or am I missing something?

**Comment by farhan-shahid** [comment]
From what I understand, Bitaddress is just a Bitcoin address generator which has nothing to do with segwit2X. Or am I missing something?
