### ISSUE TITLE
Where are the instructions for translating the thing?

### ISSUE THREAD

**Issue by ordtrogen** [pointbiz/bitaddress.org#157]
I'd like to contribute by translating the GUI but don't understand how it's organized. E.g I can see a data structure with translations into German like this:

(function (translator) {
	translator.translations["de"] = { [...]

But it twice, in two different locations, once in the file
./src/culture/de.js  
and a second time in the file
./bitaddress.org.html

Without having studied the code closely, it looks redundant. Is it, or do I need to provide "my" corresponding data structure twice, in the same way?

**Comment by MitchellCash** [comment]
`bitaddress.org.html` is just the output of the generated source files inside `src`.

So make your changes only once to `src/culture/de.js` and then generate a new `bitaddress.org.html` using Grunt.

**Comment by ordtrogen** [comment]
Perfect! Thanks.
