### ISSUE TITLE
HELP! Cannot redeem the old paper wallet

### ISSUE THREAD

**Issue by SSim00023** [pointbiz/bitaddress.org#180]
Hi

I made a paper wallet last year (04.10.17) with the BIP38 encryption on.
Yesterday i trayed to redeem it, but seems like the public and private address dont match up!
Ive used the Wallet Details og the site, and when i enter the encrypted key and the passphrase it gives me a wrong public address, so something is suddenly wrong.

The 1,6 bitcoin is visible on the blockchain, using the public address
I have a printed screen dump of the wallet createt, så everything is on there, black on white

Is it really posible that it can generate a public and private address that doesn't match up?
Hope someone can help??

**Comment by grepsuzette** [comment]
Did you find what the problem was?

**Comment by SSim00023** [comment]
Yes, thanks

I had an old downloaded version of bitaddress.org on my desktop.
That version could apparently not decrypt the BIP38 Passphrase right, so it showed me a wrong public address, with no Bitcoin on, thereby making me belive i put the bitcoint on an address I did not have acces to.

20 hours of headache later, I triad the online version, then there was no problem :-)
