### ISSUE TITLE
Can we work to support more print layouts?  Or, a super minimal key/address API

### ISSUE THREAD

**Issue by shakespeare1212** [pointbiz/bitaddress.org#207]
Hello folks,

I love this project. I use i all of the time, but can we make the code more modular?  I would like to add more lines for a transaction record (like a check book register), or I would like to make something supper small and concealable, or something that prints 6 wallets on a single letter sized page. Does anyone have time to work with me on these efforts?  We can maybe fork to a whole new project.

Thanks.

**Comment by pointbiz** [comment]
You can already print 7 wallets per letter size page.

**Comment by shakespeare1212** [comment]
Yes, but we could do a lot better.  What about letting a person personalize their wallet with their own picture?  How about inserting registry table so that they can record transactions on that account.  In this way they would not have to fire up an internet connect computer every time they wanted to check how many bitCoin (or whatever) they own.
