### ISSUE TITLE
BE CAREFUL - bitaddress SCAM !!!!!!!!! DO USE IT All my btc were Stolen with brain wallet DONT USE IT!!!!!

### ISSUE THREAD

**Issue by ungaro59** [pointbiz/bitaddress.org#217]
SCAM !!!!!!

**Comment by joma512900** [comment]
Can you put the code you used to better understand what happened to you and not fall for it?

**Comment by who-is-apo** [comment]
It's not a scam. If it was, you could probably point out the malicious code?
