### ISSUE TITLE
All the bitcoin addresses generated on this site can be found on https://privatekeys.pw/search

### ISSUE THREAD

**Issue by BhagwanParge** [pointbiz/bitaddress.org#228]
If you search using your private key on https://privatekeys.pw/search, you will be surprised to know that this bitcoin address & private key already exists in their database.

I checked & this is happening more frequently than one can imagine, this is ridiculous.

more info on,
https://www.reddit.com/r/btc/comments/lfcfhv/bitcoin_addresses_are_getting_duplicate_collision/

**Comment by BhagwanParge** [comment]
Don't you think, users of your site know this as a big issue.
Have you checked above issue.

**Comment by pointbiz** [comment]
No one should paste their private key on that site.

Your claims are false.

**Comment by BhagwanParge** [comment]
You didn't get my point.

I am saying that, the randomly generated key on this site (100% times) can be found on https://privatekeys.pw/search. So, anybody can search using private key. Now you will say, why would anybody have a private key in the first place but you need to think these keys data already exists in https://privatekeys.pw database, so these guys can search using the bitcoin address (which is not allowed currently to public)

The main question you should ask should be, as we think, this is next to impossible to generate or have same bitcoin addresses by 2 peoples.

My understanding is **privatekeys.pw** guys are generating millions of millions keys daily.

**Comment by kudusmedine07-png** [comment]
@pointbiz

**Comment by kudusmedine07-png** [comment]
> If you search using your private key on https://privatekeys.pw/search, you will be surprised to know that this bitcoin address & private key already exists in their database.
> 
> I checked & this is happening more frequently than one can imagine, this is ridiculous.
> 
> more info on, https://www.reddit.com/r/btc/comments/lfcfhv/bitcoin_addresses_are_getting_duplicate_collision/

**Comment by jessicacarr1326-web** [comment]
[https://github.com/pointbiz/bitaddress.org/issues/228](url)
