### ISSUE TITLE
Allow bulk creation of BIP38 keys

### ISSUE THREAD

**Issue by ghost** [pointbiz/bitaddress.org#26]
Should allow one to bulk create encrypted keys too on the bulk keys tab.

**Comment by austrocoin** [comment]
It would be great if there would be an option too for having different passphrases when mass produce. Lets say I need 7 addresses with different passphrase each. This option would get real powerful when an additional "export feature" (download csv + QR-images in a zip file) would be integrated - would let mass produce print products easy (for example)!

**Comment by pointbiz** [comment]
Bulk wallet tab now supports encrypted keys.

I'm not considering supporting different passphrase per address as that is too computationally intensive with BIP38.
