### ISSUE TITLE
BIP38 Mobile Safari crash

### ISSUE THREAD

**Issue by sergioabril** [pointbiz/bitaddress.org#39]
I'm not sure if it can be solved or is due to the hard BIP38 process, but every time I try to encrypt a paper wallet with  BIP38 on any iOS device (iphone/iPad), it just crashes. I'm not sure if its a memory issue or what, but I tried it on the last iPhone and iPad available on market with the same result... And would be great to have it working there, being Mobile Safari some kind of sandboxed-secured app..

https://bitcointalk.org/index.php?topic=350296.0

**Comment by PattanaiSgulrax** [comment]
pai0963019505_vyoifl
