### ISSUE TITLE
Paper Wallets: Provide copy&paste list of Bitcoin addresses

### ISSUE THREAD

**Issue by renne** [pointbiz/bitaddress.org#66]
If one generates paper wallets he either has to scan the QR codes of the Bitcoin addresses or has to enter them manually to load money on the paper wallets. This is very time consuming if creating a large number of paper wallets.

So I suggest to create a CSV list of Bitcoin addresses which can be copy&pasted.

**Comment by pointbiz** [comment]
v3.0.0 should solve this issue. You can now copy a CSV from the session log feature. If you just want the Bitcoin addresses then you have to copy/paste to a spreadsheet program then delete the column with the private keys.
