### ISSUE TITLE
BIP38 Encrypt/Decrypt Doesn't Work When Passphrase Ends With A Space Character

### ISSUE THREAD

**Issue by mrcope** [pointbiz/bitaddress.org#76]
I was learning about BIP38 today and went to bitaddress.org to see how it worked.  I created an address on the Paper Wallet tab with the 'BIP38 Encrypt?' checked and a passphrase that just so happened to end with a space.

In Wallet Details tab, when I tried to decrypt with the same passphrase, it couldn't decrypt it.  I tried removing the trailing space in the passphrase, but that didn't work either.

I went through the whole process again, this time without a trailing blank space and this time the decryption worked.

I repeated this process a few more times to make sure I hadn't made a mistake, alternating between putting a trailing space at the end and not putting a trailing space at the end of the passphrase with the same results.  Passphrases without a trailing space decrypt just fine.  Passphrases with a trailing space will not decrypt (again, trying both with the trailing space and removing the trailing space).

Here was my process in case you want to reproduce the error:
1. On 'Paper Wallet' tab, check 'BIP38 Encrypt?' and generate 1 address, using a passphrase that ends with a space character
2. Use phone to scan QR code for the encrypted private key and email it to yourself
3. Copy encrypted private key from email and paste it in the text box on the 'Wallet Details' tab
4. Enter passphrase, click 'DecryptBIP38' button, get message saying it could not decrypt

I'm using Safari 7.0.2.

**Comment by pointbiz** [comment]
Fixed in v2.9.6
