### ISSUE TITLE
Private/Public key mismatch

### ISSUE THREAD

**Issue by belgacoin** [pointbiz/bitaddress.org#90]
Hello,

Today I created a paper wallet, I checked the Pub Addr in blockchain.info and strangely enough, the newly created bitcoin address had 1 BTC on it!!
The Priv Key on the other hand didn't match with this address, I extracted the Pub Key via Armory from this Priv Key and it resulted in a different Pub Addr.

**Comment by pointbiz** [comment]
Yes, this was due to a malware browser plugin that modified the bitaddress output. There was no flaw in the bitaddress code related to this issue.

**Comment by belgacoin** [comment]
Indeed, it was a malicious Chrome add-on (Dogecoin ticker).
