### ISSUE TITLE
access 'testnet edition' from top level URL

### ISSUE THREAD

**Issue by Justin-Maxwell** [pointbiz/bitaddress.org#92]
Hi.

https://bitaddress.org/ redirects to
 bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html

it would be good if https://bitaddress.org/?testnet=true redirected to
 bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html?testnet=true

Cheers.

**Comment by pointbiz** [comment]
Thanks for the idea. I have implemented it.
https://bitaddress.org/?testnet=true
