### ISSUE TITLE
viewing details of out of range private key causes incomplete output

### ISSUE THREAD

**Issue by mruddy** [pointbiz/bitaddress.org#93]
On the "Wallet Details" tab, entering the following out of range private key value into the text box and clicking "View Details" causes an error which displays incomplete output:

```
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
```

This is the error logged in the browser console:

```
Uncaught TypeError: Cannot read property 'toBigInteger' of null
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:1861 ec.PointFp.getX
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:2026 ec.PointFp.getEncoded
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:5693 Bitcoin.ECKey.ECKey.getPub
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:5730 Bitcoin.ECKey.ECKey.getPubKeyHash
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:5735 Bitcoin.ECKey.ECKey.getBitcoinAddress
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:9332 ninja.wallets.detailwallet.populateKeyDetails
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:9323 ninja.wallets.detailwallet.viewDetails
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:6787 onclick
```

Entering `0000000000000000000000000000000000000000000000000000000000000000` generates this error in the browser console:

```
Uncaught TypeError: Cannot read property 'toBigInteger' of null
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:1861 ec.PointFp.getX
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:2026 ec.PointFp.getEncoded
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:5693 Bitcoin.ECKey.ECKey.getPub
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:5730 Bitcoin.ECKey.ECKey.getPubKeyHash
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:5735 Bitcoin.ECKey.ECKey.getBitcoinAddress
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:9332 ninja.wallets.detailwallet.populateKeyDetails
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:9323 ninja.wallets.detailwallet.viewDetails
bitaddress.org-v2.9.3-SHA1-7d47ab312789b7b3c1792e4abdb8f2d95b726d64.html:6787 onclick
```

Further, since the range of valid private key values for the secp256k1 curve, when specified in hex is [`0x1`, `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364140`], perhaps values out of range should be rejected, or displayed with a warning.
For example, the following invalid private key values seem to work without problem:

```
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364142

FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

**Comment by pointbiz** [comment]
I'm working on a fix for these issues. There are two separate issues.
1) Not propagating checksum error to the UI
2) Not triggering an error on out of range BigInteger

Related issue https://github.com/pointbiz/bitaddress.org/issues/137

**Comment by pointbiz** [comment]
Also it was reported here on the forum:
Checksum validation failed!
https://bitcointalk.org/index.php?topic=43496.msg13053307#msg13053307

Thank you for the thorough bug report. I'm putting updates for these issues in this thread.

**Comment by pointbiz** [comment]
Fixed in this commit https://github.com/pointbiz/bitaddress.org/commit/af91e78b98ac912ede907408d2b032dd10fe9ee3

**Comment by mruddy** [comment]
@pointbiz I've verified that the out of range values mentioned above now generate a warning alert. Verified with FireFox 50 and Chrome 54. Thanks!
